openapi: 3.0.3
info:
  title: REST_API
  description: BackEndのREST API仕様です
  version: 1.0.0
servers:
  - url: https://cycle-54ee5-default-rtdb.firebaseio.com/
    description: Firebase(Realtime Database)
    variables:
      port:
        enum:
          - '3000'
        default: '3000'
        description: ポート番号
tags:
  - name: marker
    description: Marker操作のAPIグループ
paths:
  /marker/create.json:
    post:
      operationId: marker_create
      summary: Marker登録API
      description: Marker登録APIです
      tags:
        - marker
      requestBody:
        description: 登録内容
        content:
          application/json:
            schema:
              type: object
              required:
                - timestamp
              properties:
                timestamp:
                  description: 登録日付(Unixミリ秒)
                  type: integer
                  format: int64
                  example: 1678150618427
                latitude:
                  description: 緯度(latitude)
                  type: number
                  example: 35.360652
                longitude:
                  description: 経度(longitude)
                  type: number
                  example: 138.727323
                altitude:
                  description: 高度(altitude)
                  type: number
                  example: 3772.123
                accuracy:
                  description: メートル単位で測定された、場所の不確実性の半径
                  type: number
                  example: 10
                altitudeAccuracy:
                  description: 高度値の精度 (メートル単位)
                  type: number
                  example: 10
                heading:
                  description: >-
                    このデバイスの水平方向の移動方向。真北からコンパスを中心に時計回りに度数で測定されます。したがって、北は 0 度、東は
                    90 度、南は 180 度などです
                  type: number
                  example: 0
                speed:
                  description: デバイスの瞬間速度 (メートル/秒)
                  type: number
                  example: 10
                comment:
                  type: object
                  description: Commentオブジェクト
                  properties:
                    id:
                      description: ID
                      type: integer
                      format: int64
                      example: 100
                    comment:
                      description: コメント文字列
                      type: string
                      example: あいうえお abc 12345
                imageId:
                  description: 画像ID
                  type: string
                  example: marker/xxxxxx
      responses:
        '200':
          description: Markerオブジェクト生成結果
          content:
            application/json:
              schema:
                type: object
                description: 生成結果ユニークID
                required:
                  - name
                properties:
                  name:
                    description: ユニークID
                    type: string
                    example: xxxxxx
    get:
      operationId: markers_get
      summary: Marker取得API
      description: Marker取得APIです
      tags:
        - marker
      parameters:
        - in: query
          name: orderBy
          schema:
            type: string
          description: 順序付け対象
        - in: query
          name: startAt
          schema:
            type: integer
            format: int64
          description: 開始(Unixミリ秒)
        - in: query
          name: endAt
          schema:
            type: integer
            format: int64
          description: 終了(Unixミリ秒)
        - in: query
          name: limitToFirst
          schema:
            type: integer
          description: 取得データ数
      responses:
        '200':
          description: MarkerオブジェクトN応答
          content:
            application/json:
              schema:
                type: object
                description: Markerオブジェクト
                additionalProperties:
                  type: object
                  description: Markerオブジェクト
                  required:
                    - id
                    - datetime
                  properties:
                    id:
                      description: ID
                      type: integer
                      format: int64
                      example: 100
                    timestamp:
                      description: 登録日付(Unixミリ秒)
                      type: integer
                      format: int64
                      example: 1678150618427
                    latitude:
                      description: 緯度(latitude)
                      type: number
                      example: 35.360652
                    longitude:
                      description: 経度(longitude)
                      type: number
                      example: 138.727323
                    altitude:
                      description: 高度(altitude)
                      type: number
                      example: 3772.123
                    accuracy:
                      description: メートル単位で測定された、場所の不確実性の半径
                      type: number
                      example: 10
                    altitudeAccuracy:
                      description: 高度値の精度 (メートル単位)
                      type: number
                      example: 10
                    heading:
                      description: >-
                        このデバイスの水平方向の移動方向。真北からコンパスを中心に時計回りに度数で測定されます。したがって、北は 0
                        度、東は 90 度、南は 180 度などです
                      type: number
                      example: 0
                    speed:
                      description: デバイスの瞬間速度 (メートル/秒)
                      type: number
                      example: 10
                    comment:
                      type: object
                      description: Commentオブジェクト
                      properties:
                        id:
                          description: ID
                          type: integer
                          format: int64
                          example: 100
                        comment:
                          description: コメント文字列
                          type: string
                          example: あいうえお abc 12345
                    imageId:
                      description: 画像ID
                      type: string
                      example: marker/xxxxxx
  /marker/select.json:
    get:
      operationId: marker_by_id
      summary: Marker取得API(ID指定)
      description: Marker取得API(ID指定)です
      tags:
        - marker
      parameters:
        - name: id
          in: path
          required: true
          example: 100
          schema:
            type: integer
      responses:
        '200':
          description: Markerオブジェクト1応答
          content:
            application/json:
              schema:
                type: object
                description: Markerオブジェクト
                required:
                  - id
                  - datetime
                properties:
                  id:
                    description: ID
                    type: integer
                    format: int64
                    example: 100
                  timestamp:
                    description: 登録日付(Unixミリ秒)
                    type: integer
                    format: int64
                    example: 1678150618427
                  latitude:
                    description: 緯度(latitude)
                    type: number
                    example: 35.360652
                  longitude:
                    description: 経度(longitude)
                    type: number
                    example: 138.727323
                  altitude:
                    description: 高度(altitude)
                    type: number
                    example: 3772.123
                  accuracy:
                    description: メートル単位で測定された、場所の不確実性の半径
                    type: number
                    example: 10
                  altitudeAccuracy:
                    description: 高度値の精度 (メートル単位)
                    type: number
                    example: 10
                  heading:
                    description: >-
                      このデバイスの水平方向の移動方向。真北からコンパスを中心に時計回りに度数で測定されます。したがって、北は 0
                      度、東は 90 度、南は 180 度などです
                    type: number
                    example: 0
                  speed:
                    description: デバイスの瞬間速度 (メートル/秒)
                    type: number
                    example: 10
                  comment:
                    type: object
                    description: Commentオブジェクト
                    properties:
                      id:
                        description: ID
                        type: integer
                        format: int64
                        example: 100
                      comment:
                        description: コメント文字列
                        type: string
                        example: あいうえお abc 12345
                  imageId:
                    description: 画像ID
                    type: string
                    example: marker/xxxxxx
