openapi: 3.0.3
info:
  title: REST_API
  description: BackEndのREST API仕様です
  version: 1.0.0
servers:
  - url: http://localhost:{port}/
    description: 開発環境
    variables:
      port:
        enum:
          - '3000'
        default: '3000'
        description: ポート番号
tags:
  - name: marker
    description: Marker操作のAPIグループ
paths:
  /marker/create:
    post:
      operationId: marker_create
      summary: Marker登録API
      description: Marker登録APIです
      tags:
        - marker
      requestBody:
        description: 登録内容
        content:
          application/json:
            schema:
              type: object
              required:
                - datetime
              properties:
                datetime:
                  description: 登録日付(Unixミリ秒)
                  type: integer
                  format: int64
                  example: 1678150618427
                lat:
                  description: 緯度(latitude)
                  type: number
                  example: 35.360652
                lng:
                  description: 経度(longitude)
                  type: number
                  example: 138.727323
                alt:
                  description: 高度(altitude)
                  type: number
                  example: 3772.123
                comment:
                  type: object
                  description: Commentオブジェクト
                  properties:
                    id:
                      description: ID
                      type: integer
                      format: int64
                      example: 100
                    comment:
                      description: コメント文字列
                      type: string
                      example: あいうえお abc 12345
                imageId:
                  description: 画像ID
                  type: integer
                  example: 100101
      responses:
        '200':
          description: Markerオブジェクト1応答
          content:
            application/json:
              schema:
                type: object
                description: Markerオブジェクト
                required:
                  - id
                  - datetime
                properties:
                  id:
                    description: ID
                    type: integer
                    format: int64
                    example: 100
                  datetime:
                    description: 登録日付(Unixミリ秒)
                    type: integer
                    format: int64
                    example: 1678150618427
                  lat:
                    description: 緯度(latitude)
                    type: number
                    example: 35.360652
                  lng:
                    description: 経度(longitude)
                    type: number
                    example: 138.727323
                  alt:
                    description: 高度(altitude)
                    type: number
                    example: 3772.123
                  comment:
                    type: object
                    description: Commentオブジェクト
                    properties:
                      id:
                        description: ID
                        type: integer
                        format: int64
                        example: 100
                      comment:
                        description: コメント文字列
                        type: string
                        example: あいうえお abc 12345
                  imageId:
                    description: 画像ID
                    type: integer
                    example: 100101
  /marker/{id}:
    get:
      operationId: marker_by_id
      summary: Marker取得API(ID指定)
      description: Marker取得API(ID指定)です
      tags:
        - marker
      parameters:
        - name: id
          in: path
          required: true
          example: 100
          schema:
            type: integer
      responses:
        '200':
          description: Markerオブジェクト1応答
          content:
            application/json:
              schema:
                type: object
                description: Markerオブジェクト
                required:
                  - id
                  - datetime
                properties:
                  id:
                    description: ID
                    type: integer
                    format: int64
                    example: 100
                  datetime:
                    description: 登録日付(Unixミリ秒)
                    type: integer
                    format: int64
                    example: 1678150618427
                  lat:
                    description: 緯度(latitude)
                    type: number
                    example: 35.360652
                  lng:
                    description: 経度(longitude)
                    type: number
                    example: 138.727323
                  alt:
                    description: 高度(altitude)
                    type: number
                    example: 3772.123
                  comment:
                    type: object
                    description: Commentオブジェクト
                    properties:
                      id:
                        description: ID
                        type: integer
                        format: int64
                        example: 100
                      comment:
                        description: コメント文字列
                        type: string
                        example: あいうえお abc 12345
                  imageId:
                    description: 画像ID
                    type: integer
                    example: 100101
